language: python
python:
- '3.8'
install:
- pip install ansible==2.9
script:
- ansible -i hosts all -m ping
- ansible-playbook -i hosts base.yaml
env:
  global:
  - ANSIBLE_HOST_KEY_CHECKING='false'
  - ANSIBLE_VAULT_PASSWORD_FILE='vault-password'
  - ANSIBLE_REMOTE_USER='root'
before_install:
- openssl aes-256-cbc -K $encrypted_e8b9f665f844_key -iv $encrypted_e8b9f665f844_iv
  -in ssh.enc -out ssh -d
- openssl aes-256-cbc -K $encrypted_ade06c989c88_key -iv $encrypted_ade06c989c88_iv
  -in vault-password.enc -out vault-password -d
- eval "$(ssh-agent -s)"
- chmod 600 ./ssh
- ssh-add ./ssh
